routes/admin.php
<?php

// Dashboard
Route::get('/', 'DashboardController@dashboard')
    ->name('dashboard');

Route::resource('users', 'UserController')
    ->only('index')
    ->middleware('can:view-users');
Route::resource('users', 'UserController')
    ->except(['show', 'index'])
    ->middleware('can:manage-users');
Route::get('users/iiko', 'UserController@iiko')
    ->name('users.iiko')
    ->middleware('can:manage-users');

Route::resource('customers', 'CustomerController')
    ->only('index')
    ->middleware('can:view-customers');
Route::resource('customers', 'CustomerController')
    ->except(['index', 'show'])
    ->middleware('can:manage-customers');

Route::resource('birthdays', 'BirthdaysController')
    ->only('index')
    ->middleware('can:view-birthdays');

Route::resource('cities', 'CityController')
    ->only('index')
    ->middleware('can:view-cities');
Route::resource('cities', 'CityController')
    ->except(['index', 'show'])
    ->middleware('can:manage-cities');
Route::get('cities/iiko', 'CityController@iiko')
    ->name('cities.iiko')
    ->middleware('can:manage-cities');

Route::resource('roles', 'RoleController')
    ->only('index')
    ->middleware('can:view-roles');
Route::resource('roles', 'RoleController')
    ->except(['index', 'show'])
    ->middleware('can:manage-roles');
Route::post('permissions/store', 'RoleController@storePermission')
    ->name('permissions.store')
    ->middleware('can:manage-permissions');

Route::resource('terminals', 'TerminalController')
    ->only('index')
    ->middleware('can:view-terminals');
Route::resource('terminals', 'TerminalController')
    ->except(['index', 'show'])
    ->middleware('can:manage-terminals');
Route::get('terminals/iiko', 'TerminalController@iiko')
    ->name('terminals.iiko')
    ->middleware('can:manage-terminals');

Route::resource('categories', 'CategoryController')
    ->only('index')
    ->middleware('can:view-categories');
Route::resource('categories', 'CategoryController')
    ->except(['index', 'show'])
    ->middleware('can:manage-categories');
Route::get('categories/iiko', 'CategoryController@iiko')
    ->name('categories.iiko')
    ->middleware('can:manage-categories');

Route::resource('product-groups', 'ProductGroupController')
    ->only('index')
    ->middleware('can:view-product-groups');
Route::resource('product-groups', 'ProductGroupController')
    ->except(['index', 'show'])
    ->middleware('can:manage-product-groups');
Route::get('product-groups/iiko', 'ProductGroupController@iiko')
    ->name('product-groups.iiko')
    ->middleware('can:manage-product-groups');

Route::resource('products', 'ProductController')
    ->only('index')
    ->middleware('can:view-products');
Route::resource('products', 'ProductController')
    ->except(['index', 'show'])
    ->middleware('can:manage-products');
Route::post('products/{product}/remove-image', 'ProductController@removeImage')
    ->name('products.removeImage')
    ->middleware('can:manage-products');
Route::get('products/iiko', 'ProductController@iiko')
    ->name('products.iiko')
    ->middleware('can:manage-products');

Route::resource('achievements', 'AchievementController')
    ->only('index')
    ->middleware('can:view-achievements');
Route::resource('achievements', 'AchievementController')
    ->except(['index', 'show'])
    ->middleware('can:manage-achievements');
Route::post('achievements/{achievement}/remove-image', 'AchievementController@removeImage')
    ->name('achievements.removeImage')
    ->middleware('can:manage-achievements');

Route::resource('pages', 'PageController')
    ->only('index')
    ->middleware('can:view-pages');
Route::resource('pages', 'PageController')
    ->except(['index', 'show'])
    ->middleware('can:manage-pages');
Route::post('pages/{page}/remove-image', 'PageController@removeImage')
    ->name('pages.removeImage')
    ->middleware('can:manage-pages');

Route::resource('posts', 'PostController')
    ->only('index')
    ->middleware('can:view-posts');
Route::resource('posts', 'PostController')
    ->except(['index', 'show'])
    ->middleware('can:manage-posts');
Route::post('posts/{post}/remove-image', 'PostController@removeImage')
    ->name('posts.removeImage')
    ->middleware('can:manage-posts');

Route::resource('promos', 'PromoController')
    ->only('index')
    ->middleware('can:view-promos');
Route::get('promos/random', 'PromoController@randomQr')
    ->name('promos.random')
    ->middleware('can:manage-promos');
Route::resource('promos', 'PromoController')
    ->except(['index', 'show'])
    ->middleware('can:manage-promos');

Route::get('orders/game', 'OrderController@gameStats')
    ->name('orders.game')
    ->middleware('can:manage-orders');
Route::get('orders/iiko', 'OrderController@iiko')
    ->name('orders.iiko')
    ->middleware('can:manage-orders');
Route::resource('orders', 'OrderController')
    ->only(['index', 'show'])
    ->middleware('can:view-orders');
Route::resource('orders', 'OrderController')
    ->except(['index', 'show'])
    ->middleware('can:manage-orders');
Route::post('orders/sendtoiiko/{order}', 'OrderController@sendToIiko')
    ->name('orders.sendToIiko')
    ->middleware('can:manage-orders');

Route::get('settings', 'SettingsController@index')
    ->name('settings.index')
    ->middleware('can:view-settings');
Route::put('settings', 'SettingsController@update')
    ->name('settings.update')
    ->middleware('can:manage-settings');

Route::resource('slides', 'SlideController')
    ->only(['index'])
    ->middleware('can:view-slides');
Route::resource('slides', 'SlideController')
    ->except(['index', 'show'])
    ->middleware('can:manage-slides');
Route::post('slides/{slide}/remove-image', 'SlideController@removeImage')
    ->name('slides.removeImage')
    ->middleware('can:manage-slides');

Route::get('opinions', 'OpinionController@index')
    ->name('opinions.index')
    ->middleware('can:view-opinions');

Route::get('market-bonuses', 'MarketBonusController@index')
    ->name('marketBonuses.index')
    ->middleware('can:view-market-bonuses');

Route::resource('bowl-ingredients', 'BowlIngredientController')
    ->only('index')
    ->middleware('can:view-bowl-ingredients');
Route::resource('bowl-ingredients', 'BowlIngredientController')
    ->except(['index', 'show'])
    ->middleware('can:manage-bowl-ingredients');

Route::get('translations', 'SettingsController@translations')
    ->name('settings.translations')
    ->middleware('can:manage-translations');

Route::post('upload-image', 'DashboardController@uploadImage');

Route::resource('marks', 'MarkController')
    ->only('index')
    ->middleware('can:view-marks');
Route::resource('marks', 'MarkController')
    ->except(['index', 'show'])
    ->middleware('can:manage-marks');

// Telegram bot
Route::resource('telegram/groups', 'TelegramGroupController')
    ->only('index')
    ->middleware('can:view-telegram-groups');
Route::resource('telegram/groups', 'TelegramGroupController')
    ->except(['index', 'show'])
    ->middleware('can:manage-telegram-groups');
Route::post(
    'telegram/groups/{group}/send-message',
    'TelegramGroupController@sendMessage'
)->name('groups.sendMessage')
    ->middleware('can:manage-telegram-groups');

Route::resource('telegram/tasks', 'TelegramTaskController')
    ->only('index')
    ->middleware('can:view-telegram-tasks');
Route::resource('telegram/tasks', 'TelegramTaskController')
    ->except(['index', 'show'])
    ->middleware('can:manage-telegram-tasks');
Route::get('telegram/export', 'TelegramTaskController@export')
    ->name('tasks.export')
    ->middleware('can:view-telegram-tasks');

// Artisan
Route::get('artisan', 'DashboardController@artisan')
    ->name('artisan')
    ->middleware('can:run-commands');

Route::resource('callbacks', 'CallbackController')
    ->only('index')
    ->middleware('can:view-callbacks');

Route::resource('notifications', 'NotificationsController')
    ->only(['create', 'store', 'index'])
    ->middleware('can:manage-notifications');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index')
    ->name('index');
Route::get('test', 'SiteController@test')
    ->name('test');

// Opinions
Route::get('r/{opinion:slug}', 'SiteController@opinion')
    ->name('opinion');
Route::post('r/{opinion:slug}', 'SiteController@opinionSave')
    ->name('opinion.save');
Route::get('qr/{promo:qr_code}', 'SiteController@qrCode')
    ->name('qr');
Route::get('qro', 'SiteController@qrOpinion')
    ->name('qrOpinion');

// Application QR code redirect
Route::get('{type}', 'SiteController@qrStore')
    ->where('type', 'ios|android')
    ->name('qrStore');
Route::post('{type}', 'SiteController@qrStoreSave')
    ->where('type', 'ios|android')
    ->name('qrStoreSave');

// Payments
Route::post('liqpay-status', 'SiteController@liqpayStatus')
    ->name('liqpayStatus');

Auth::routes();

// Telegram bot
Route::post('telegram/webhook', 'SiteController@telegramWebhook');

Route::middleware('auth')->group(function () {
    Route::get('account', 'AccountController@index')
        ->name('account');
    Route::put('account', 'AccountController@update')
        ->name('updateAccount');

    Route::post('subscriptions', 'PushController@update');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('lang', 'AjaxController@getLangTexts');
    Route::any('basket/add', 'BasketController@add')
        ->name('basket.add');
    Route::any('basket/repeat/{order}', 'BasketController@repeat')
        ->name('basket.repeat');
    Route::any('basket/remove', 'BasketController@remove')
        ->name('basket.remove');
    Route::any('order', 'BasketController@order')
        ->name('basket.order');
    Route::get('order-track/{order}', 'AjaxController@orderTrack')
        ->name('basket.orderTrack');
    Route::any('basket', 'BasketController@basket')
        ->name('basket');
    Route::get('streets.json', 'AjaxController@streets');
    Route::post('callback', 'AjaxController@callback')
        ->name('callback');
    Route::get('find-bowl', 'AjaxController@findBowl');
    Route::get('how-many-kotcoins', 'AjaxController@howManyKotcoins')
        ->name('howManyKotcoins');
    Route::put('game-score', 'AjaxController@gameScore')
        ->name('gameScore');
    Route::get('valid-promo', 'AjaxController@validPromo')
        ->name('validPromo');
});

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileRequest;
use App\Models\Order;
use Illuminate\Http\Request;

class AccountController extends Controller
{
    /**
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        if (! config('site.personal_cabinet_enabled')) {
            return redirect('admin');
        }
        return view('site.account.profile', [
            // 'orders' => $request->user()->orders()->orderBy('created_at', 'desc')->paginate(10),
            'bonusTransactions' => $request->user()->transactions,
            'lastOrder' => $request->user()
                ->phoneOrders()
                ->orderBy('created_at', 'desc')
                ->whereStatus(Order::ORDER_STATUS_CLOSED)
                ->first(),
        ]);
    }

    /**
     *
     */
    public function update(ProfileRequest $request)
    {
        $data = $request->validated();
        if ($request->password) {
            $data['password'] = bcrypt($request->password);
        } else {
            unset($data['password']);
        }

        $request->user()->update($data);
        return back();
    }
}

resources/views/site/account/bonuses.blade.php
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Дата</th>
            <th>Сумма</th>
            <th>Заказ</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($bonusTransactions as $transaction)
        <tr>
            <td>{{ $transaction->created_at }}</td>
            <td>{{ $transaction->sum }}</td>
            <td><a href="#">({{ $transaction->order_id }})</a> {{ __('shop.price', [$transaction->sum]) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/site/account/orders.blade.php
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th style="width: 10px">#</th>
            <th>Дата</th>
            <th>Блюда</th>
            <th>Сумма</th>
            <th>Начисленные бонусы</th>
            <th>Статус</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach ($orders as $order)
        <tr>
            <td>{{ $order->id }}</td>
            <td>{{ $order->ordered_at }}</td>
            <td>{{ $order->dishes }}</td>
            <td>{{ __('shop.price', [$order->sum]) }}</td>
            <td>{{ $order->bonuses }}</td>
            <td>{{ __('shop.order_statuses.' . $order->status) }}</td>
            <td><a class="btn btn-success" href="{{ route('ajax.basket.repeat', $order) }}">Повторить</a></td>
        </tr>
        @endforeach
    </tbody>
</table>
{{ $orders->links() }}

resources/views/site/account/profile.blade.php
@extends('site.app')

@section('content')

<section>
    <div class="os-container">
        <div class="search-result">
            {{ __('Bonuses and history') }}
        </div>

        <div class="account-catcoin">
            <div class="os-child-width-1-2 os-grid">
                <div class="os-flex">
                    <div class="catuser os-flex os-flex-middle os-flex-center">
                        <img loading="lazy" src="{{ asset('images/site/catcoin.svg') }}" alt="kotcoin">
                    </div>
                    <div>
                        <div class="title">
                            {{ __('On your wallet') }}:
                        </div>
                        <div class="os-flex os-flex-wrap os-flex-bottom">
                            <div class="count-catcoin">
                                <div>
                                    {{ auth()->user()->kotcoins }}
                                </div>
                                <div>
                                    {{ __('kotcoins') }}
                                </div>
                            </div>
                            <div class="description">
                                <p>
                                    {{ __('Download our app') }}
                                </p>
                            </div>
                        </div>

                    </div>
                </div>
                <div>

                    <div class="title">
                        {{ __('Change profile data') }}:
                    </div>
                    <form action="{{ route('updateAccount') }}" method="post">
                        @csrf
                        @method('PUT')

                        <div>
                            <input type="text" name="name" class="os-input" value="{{ old('name', auth()->user()->name) }}" placeholder="{{ __('Name') }}">
                            @error('name')
                                <strong>{{ $message }}</strong>
                            @enderror
                            <input type="phone" disabled class="os-input" value="{{ old('phone', auth()->user()->phone) }}" pattern="{{ config('auth.phone_pattern') }}" placeholder="{{ __('Phone') }}">
                            @error('phone')
                                <strong>{{ $message }}</strong>
                            @enderror
                        </div>
                        <div>
                            <input type="email" name="email" class="os-input" value="{{ old('email', auth()->user()->email) }}" placeholder="{{ __('E-Mail Address') }}">
                            @error('email')
                                <strong>{{ $message }}</strong>
                            @enderror
                            <input type="date" readonly class="os-input" value="{{ old('birthday', auth()->user()->birthday ?  auth()->user()->birthday->format('Y-m-d') : null) }}" placeholder="{{ __('Birthday') }}">
                            @error('birthday')
                                <strong>{{ $message }}</strong>
                            @enderror
                        </div>
                        <div>
                            <input type="password" name="password" class="os-input" placeholder="{{ __('Password') }}">
                            @error('password')
                                <strong>{{ $message }}</strong>
                            @enderror
                            <input type="password" name="password_confirmation" class="os-input" placeholder="{{ __('Confirm Password') }}">
                            <button class="btn-link">{{ __('Save') }}</button>
                        </div>
                    </form>

                </div>
            </div>

            @isset($lastOrder)
            <div class="last-see">
                {{ __('We saw at') }}: {{ $lastOrder->created_at->format('d.m.Y') }}
            </div>
            @endisset
        </div>

        <div class="catalog-items">
            @isset($lastOrder)
            <span class="title-02">{{ __('At that day you order') }}:</span>
            <div class="os-grid">
                @foreach ($lastOrder->products()->active()->activeCategory()->get() as $product)
                    @include('site.partials.productCatalogItem', $product)
                @endforeach
            </div>
            @endisset

            <div class="os-description">
                {!! $page->meta->content ?? '' !!}
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/site/account/settings.blade.php
<form action="{{ route('account') }}" method="post">
    @csrf

    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">{{ __('Name') }}</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror"
                   value="{{ old('name', auth()->user()->name) }}"
                   placeholder="{{ __('Name') }}" required autocomplete="name">
        </div>
        @error('name')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>

    <div class="form-group row">
        <label for="phone" class="col-sm-2 col-form-label">{{ __('Phone') }}</label>
        <div class="col-sm-10">
            <input type="tel" name="phone" id="phone" class="form-control @error('phone') is-invalid @enderror"
                   value="{{ old('phone', auth()->user()->phone) }}" pattern="{{ config('auth.phone_pattern') }}"
                   placeholder="{{ __('Phone') }}" required autocomplete="phone">
        </div>
        @error('phone')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>

    <div class="form-group row">
        <label for="phone" class="col-sm-2 col-form-label">{{ __('E-Mail Address') }}</label>
        <div class="col-sm-10">
            <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email', auth()->user()->email) }}"
               placeholder="{{ __('E-Mail Address') }}" required autocomplete="email">
        </div>
        @error('email')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>

    <div class="form-group row">
        <label for="phone" class="col-sm-2 col-form-label">{{ __('Birthday') }}</label>
        <div class="col-sm-10">
            <input type="date" name="birthday" class="form-control @error('birthday') is-invalid @enderror" value="{{ old('birthday', auth()->user()->birthday ?  auth()->user()->birthday->format('Y-m-d') : null) }}"
               placeholder="{{ __('Birthday') }}" required autocomplete="birthday">
        </div>


        @error('birthday')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>

    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">{{ __('Password') }}</label>
        <div class="col-sm-10">
            <input type="password" class="form-control @error('password') is-invalid @enderror"
               placeholder="{{ __('Password') }}" required autocomplete="new-password">
        </div>

        @error('password')
            <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </div>
        @enderror
    </div>

    <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
            <button type="submit" class="btn btn-danger">Зберегти</button>
        </div>
    </div>
</form>