routes/admin.php
<?php

// Dashboard
Route::get('/', 'DashboardController@dashboard')
    ->name('dashboard');

Route::resource('users', 'UserController')
    ->only('index')
    ->middleware('can:view-users');
Route::resource('users', 'UserController')
    ->except(['show', 'index'])
    ->middleware('can:manage-users');
Route::get('users/iiko', 'UserController@iiko')
    ->name('users.iiko')
    ->middleware('can:manage-users');

Route::resource('customers', 'CustomerController')
    ->only('index')
    ->middleware('can:view-customers');
Route::resource('customers', 'CustomerController')
    ->except(['index', 'show'])
    ->middleware('can:manage-customers');

Route::resource('birthdays', 'BirthdaysController')
    ->only('index')
    ->middleware('can:view-birthdays');

Route::resource('cities', 'CityController')
    ->only('index')
    ->middleware('can:view-cities');
Route::resource('cities', 'CityController')
    ->except(['index', 'show'])
    ->middleware('can:manage-cities');
Route::get('cities/iiko', 'CityController@iiko')
    ->name('cities.iiko')
    ->middleware('can:manage-cities');

Route::resource('roles', 'RoleController')
    ->only('index')
    ->middleware('can:view-roles');
Route::resource('roles', 'RoleController')
    ->except(['index', 'show'])
    ->middleware('can:manage-roles');
Route::post('permissions/store', 'RoleController@storePermission')
    ->name('permissions.store')
    ->middleware('can:manage-permissions');

Route::resource('terminals', 'TerminalController')
    ->only('index')
    ->middleware('can:view-terminals');
Route::resource('terminals', 'TerminalController')
    ->except(['index', 'show'])
    ->middleware('can:manage-terminals');
Route::get('terminals/iiko', 'TerminalController@iiko')
    ->name('terminals.iiko')
    ->middleware('can:manage-terminals');

Route::resource('categories', 'CategoryController')
    ->only('index')
    ->middleware('can:view-categories');
Route::resource('categories', 'CategoryController')
    ->except(['index', 'show'])
    ->middleware('can:manage-categories');
Route::get('categories/iiko', 'CategoryController@iiko')
    ->name('categories.iiko')
    ->middleware('can:manage-categories');

Route::resource('product-groups', 'ProductGroupController')
    ->only('index')
    ->middleware('can:view-product-groups');
Route::resource('product-groups', 'ProductGroupController')
    ->except(['index', 'show'])
    ->middleware('can:manage-product-groups');
Route::get('product-groups/iiko', 'ProductGroupController@iiko')
    ->name('product-groups.iiko')
    ->middleware('can:manage-product-groups');

Route::resource('products', 'ProductController')
    ->only('index')
    ->middleware('can:view-products');
Route::resource('products', 'ProductController')
    ->except(['index', 'show'])
    ->middleware('can:manage-products');
Route::post('products/{product}/remove-image', 'ProductController@removeImage')
    ->name('products.removeImage')
    ->middleware('can:manage-products');
Route::get('products/iiko', 'ProductController@iiko')
    ->name('products.iiko')
    ->middleware('can:manage-products');

Route::resource('achievements', 'AchievementController')
    ->only('index')
    ->middleware('can:view-achievements');
Route::resource('achievements', 'AchievementController')
    ->except(['index', 'show'])
    ->middleware('can:manage-achievements');
Route::post('achievements/{achievement}/remove-image', 'AchievementController@removeImage')
    ->name('achievements.removeImage')
    ->middleware('can:manage-achievements');

Route::resource('pages', 'PageController')
    ->only('index')
    ->middleware('can:view-pages');
Route::resource('pages', 'PageController')
    ->except(['index', 'show'])
    ->middleware('can:manage-pages');
Route::post('pages/{page}/remove-image', 'PageController@removeImage')
    ->name('pages.removeImage')
    ->middleware('can:manage-pages');

Route::resource('posts', 'PostController')
    ->only('index')
    ->middleware('can:view-posts');
Route::resource('posts', 'PostController')
    ->except(['index', 'show'])
    ->middleware('can:manage-posts');
Route::post('posts/{post}/remove-image', 'PostController@removeImage')
    ->name('posts.removeImage')
    ->middleware('can:manage-posts');

Route::resource('promos', 'PromoController')
    ->only('index')
    ->middleware('can:view-promos');
Route::get('promos/random', 'PromoController@randomQr')
    ->name('promos.random')
    ->middleware('can:manage-promos');
Route::resource('promos', 'PromoController')
    ->except(['index', 'show'])
    ->middleware('can:manage-promos');

Route::get('orders/game', 'OrderController@gameStats')
    ->name('orders.game')
    ->middleware('can:manage-orders');
Route::get('orders/iiko', 'OrderController@iiko')
    ->name('orders.iiko')
    ->middleware('can:manage-orders');
Route::resource('orders', 'OrderController')
    ->only(['index', 'show'])
    ->middleware('can:view-orders');
Route::resource('orders', 'OrderController')
    ->except(['index', 'show'])
    ->middleware('can:manage-orders');
Route::post('orders/sendtoiiko/{order}', 'OrderController@sendToIiko')
    ->name('orders.sendToIiko')
    ->middleware('can:manage-orders');

Route::get('settings', 'SettingsController@index')
    ->name('settings.index')
    ->middleware('can:view-settings');
Route::put('settings', 'SettingsController@update')
    ->name('settings.update')
    ->middleware('can:manage-settings');

Route::resource('slides', 'SlideController')
    ->only(['index'])
    ->middleware('can:view-slides');
Route::resource('slides', 'SlideController')
    ->except(['index', 'show'])
    ->middleware('can:manage-slides');
Route::post('slides/{slide}/remove-image', 'SlideController@removeImage')
    ->name('slides.removeImage')
    ->middleware('can:manage-slides');

Route::get('opinions', 'OpinionController@index')
    ->name('opinions.index')
    ->middleware('can:view-opinions');

Route::get('market-bonuses', 'MarketBonusController@index')
    ->name('marketBonuses.index')
    ->middleware('can:view-market-bonuses');

Route::resource('bowl-ingredients', 'BowlIngredientController')
    ->only('index')
    ->middleware('can:view-bowl-ingredients');
Route::resource('bowl-ingredients', 'BowlIngredientController')
    ->except(['index', 'show'])
    ->middleware('can:manage-bowl-ingredients');

Route::get('translations', 'SettingsController@translations')
    ->name('settings.translations')
    ->middleware('can:manage-translations');

Route::post('upload-image', 'DashboardController@uploadImage');

Route::resource('marks', 'MarkController')
    ->only('index')
    ->middleware('can:view-marks');
Route::resource('marks', 'MarkController')
    ->except(['index', 'show'])
    ->middleware('can:manage-marks');

// Telegram bot
Route::resource('telegram/groups', 'TelegramGroupController')
    ->only('index')
    ->middleware('can:view-telegram-groups');
Route::resource('telegram/groups', 'TelegramGroupController')
    ->except(['index', 'show'])
    ->middleware('can:manage-telegram-groups');
Route::post(
    'telegram/groups/{group}/send-message',
    'TelegramGroupController@sendMessage'
)->name('groups.sendMessage')
    ->middleware('can:manage-telegram-groups');

Route::resource('telegram/tasks', 'TelegramTaskController')
    ->only('index')
    ->middleware('can:view-telegram-tasks');
Route::resource('telegram/tasks', 'TelegramTaskController')
    ->except(['index', 'show'])
    ->middleware('can:manage-telegram-tasks');
Route::get('telegram/export', 'TelegramTaskController@export')
    ->name('tasks.export')
    ->middleware('can:view-telegram-tasks');

// Artisan
Route::get('artisan', 'DashboardController@artisan')
    ->name('artisan')
    ->middleware('can:run-commands');

Route::resource('callbacks', 'CallbackController')
    ->only('index')
    ->middleware('can:view-callbacks');

Route::resource('notifications', 'NotificationsController')
    ->only(['create', 'store', 'index'])
    ->middleware('can:manage-notifications');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index')
    ->name('index');
Route::get('test', 'SiteController@test')
    ->name('test');

// Opinions
Route::get('r/{opinion:slug}', 'SiteController@opinion')
    ->name('opinion');
Route::post('r/{opinion:slug}', 'SiteController@opinionSave')
    ->name('opinion.save');
Route::get('qr/{promo:qr_code}', 'SiteController@qrCode')
    ->name('qr');
Route::get('qro', 'SiteController@qrOpinion')
    ->name('qrOpinion');

// Application QR code redirect
Route::get('{type}', 'SiteController@qrStore')
    ->where('type', 'ios|android')
    ->name('qrStore');
Route::post('{type}', 'SiteController@qrStoreSave')
    ->where('type', 'ios|android')
    ->name('qrStoreSave');

// Payments
Route::post('liqpay-status', 'SiteController@liqpayStatus')
    ->name('liqpayStatus');

Auth::routes();

// Telegram bot
Route::post('telegram/webhook', 'SiteController@telegramWebhook');

Route::middleware('auth')->group(function () {
    Route::get('account', 'AccountController@index')
        ->name('account');
    Route::put('account', 'AccountController@update')
        ->name('updateAccount');

    Route::post('subscriptions', 'PushController@update');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('lang', 'AjaxController@getLangTexts');
    Route::any('basket/add', 'BasketController@add')
        ->name('basket.add');
    Route::any('basket/repeat/{order}', 'BasketController@repeat')
        ->name('basket.repeat');
    Route::any('basket/remove', 'BasketController@remove')
        ->name('basket.remove');
    Route::any('order', 'BasketController@order')
        ->name('basket.order');
    Route::get('order-track/{order}', 'AjaxController@orderTrack')
        ->name('basket.orderTrack');
    Route::any('basket', 'BasketController@basket')
        ->name('basket');
    Route::get('streets.json', 'AjaxController@streets');
    Route::post('callback', 'AjaxController@callback')
        ->name('callback');
    Route::get('find-bowl', 'AjaxController@findBowl');
    Route::get('how-many-kotcoins', 'AjaxController@howManyKotcoins')
        ->name('howManyKotcoins');
    Route::put('game-score', 'AjaxController@gameScore')
        ->name('gameScore');
    Route::get('valid-promo', 'AjaxController@validPromo')
        ->name('validPromo');
});

resources/views/site/modals/bowlConstructor.blade.php
<div class="os-modal os-modal-bowles">
    <div class="modal-content os-text-center os-position-relative">
        <button class="modal-icon-close">
            <img src="{{ asset('images/site/close.svg')}}" alt="close">
        </button>
        <div class="top-modal-form">
            {{ __('shop.bowl_constructor.title') }}
        </div>
        <div class="title-form os-text-uppercase">
            {{ __('shop.bowl_constructor.description') }}
        </div>

        <bowl-constructor
            :ingredients='@json(\App\Models\BowlIngredient::getIngredientsTreeInArray())'
        />
    </div>
</div>

<div class="mobile-bowl">
    <div class="mobile-menu-content os-position-relative">
        <div class="top-mobile-menu">
            {{ __('shop.bowl_constructor.title') }}
        </div>
        <button class="menu-button-close">
            <img src="{{ asset('images/site/close.svg')}}" alt="close">
        </button>
        <div class="bowl-content-mb os-text-center">
            <div class="title-form os-text-uppercase">
                {{ __('shop.bowl_constructor.description') }}
            </div>

            <bowl-constructor
                :ingredients='@json(\App\Models\BowlIngredient::getIngredientsTreeInArray())'
            />
        </div>
    </div>
</div>

resources/views/site/modals/callback.blade.php
<div class="os-modal os-modal-callback">
    <div class="modal-content os-text-center os-position-relative">
        <button class="modal-icon-close">
            <img src="{{ asset('images/site/close.svg')}}" alt="close">
        </button>
        <button class="menu-button-close">
            <img src="{{ asset('images/site/close.svg')}}" alt="close">
        </button>
        <div class="top-modal-form">
            {{ __('Connect manager') }}
        </div>
        <div class="callback-pc">
            <div class="title-form os-text-uppercase">
                {{ __('Send message for connect') }}
            </div>
            <form action="{{ route('ajax.callback') }}" method="POST">
                @csrf

                <input name="phone" type="tel" class="os-input" placeholder="{{ __('Enter phone') }}" required>
                <input name="name" type="text" class="os-input" placeholder="{{ __('Enter name') }}" required>
                {{-- <div class="location location-header">
                    <select class="select" onchange="location = this.value;">
                        @foreach(app('city')->all() as $city)
                            <option value="{{ route('cityIndex', $city) }}"{{ app('city')->id === $city->id ? ' selected' : '' }}>{{ $city->name }}</option>
                        @endforeach
                    </select>
                    <span class="myarrow"></span>
                </div> --}}
                <textarea name="comment" class="os-textarea" placeholder="{{ __('Enter comment') }}" rows="6"></textarea>
                <div class="description">
                    <button class="os-link-order">
                        {{ __('Send') }}
                    </button>
                </div>
            </form>
        </div>
        <div class="callback-mobile">
            <div class="title-form os-text-uppercase">
                {!! __('Choose callback way') !!}
            </div>

            <div class="box-icon-manager">
                <a href="https://telegram.me/Kotosushi_bot">
                    <img loading="lazy" src="{{ asset('images/site/icon-call-01.png')}}" alt="telegram">
                    <span>Телеграм</span>
                </a>
                @if (config('site.jivochat'))
                    <a href="javascript:jivo_api.open()">
                        <img loading="lazy" src="{{ asset('images/site/icon-call-02.png')}}" alt="chat">
                        <span>Чат на сайте</span>
                    </a>
                @endif
                <a href="viber://pa?chatURI=kotobot">
                    <img loading="lazy" src="{{ asset('images/site/icon-call-03.png')}}" alt="viber">
                    <span>Вайбер</span>
                </a>
                <a href="tel:+380986689999">
                    <img loading="lazy" src="{{ asset('images/site/icon-call-04.png')}}" alt="phone">
                    <span>По телефону</span>
                </a>
            </div>
        </div>
    </div>
</div>

resources/views/site/modals/delivery.blade.php
<div class="os-modal os-modal-delivery">
    <div class="modal-content os-text-center os-position-relative">
        <div class="logo-type">
            <img loading="lazy" src="{{ asset('images/site/logo_lg.svg')}}" alt="logo">
        </div>
        <h3>
            {{ __('Hellp!') }}
        </h3>
        <p>
            Доставить за 39 минут<br>
            по этому адресу?
        </p>
        <div class="delivery-select">
            <select class="select">
                <option selected>Днепр</option>
                <option>Харьков</option>
                <option>Киев</option>
                <option>Хмельницкий</option>
            </select>
            <span class="myarrow"></span>
        </div>
        <div class="delivery-select">
            <select class="select">
                <option selected>Улица</option>
                <option>Улица</option>
                <option>Улица</option>
                <option>Улица</option>
            </select>
            <span class="myarrow"></span>
        </div>
        <div class="os-flex os-flex-between">
            <div class="label-text">
                <label>Дом</label>
                <div class="os-form-controls">
                    <input type="text" class="os-input" placeholder="">
                </div>
            </div>
            <div class="label-text">
                <label>Квартира</label>
                <div class="os-form-controls">
                    <input type="text" class="os-input" placeholder="">
                </div>
            </div>
        </div>
        <div class="description os-text-center">
            <button class="os-link-order" type="submit" form="basket-form" name="callback" value="0">
                {{ __('Verify') }}
            </button>
        </div>
        <div>
            <button class="link-modal modal-close">
                {{ __('Skip') }}
            </button>
        </div>
        <button class="modal-icon-close">
            <img src="{{ asset('images/site/close.svg')}}" alt="close">
        </button>
    </div>
</div>

resources/views/site/modals/location.blade.php
<div class="os-modal os-modal-location">
    <div class="modal-content os-text-center os-position-relative">
        <div class="logo-type">
            <img loading="lazy" src="{{ asset('images/site/logo_lg.png') }}" alt="">
        </div>
        <h3>
            {{ __('Hellp!') }}
        </h3>
        <p>
            {!! __('Select city') !!}
        </p>
        <div class="location location-header">
            <select class="select" id="welcome-select-city" name="select_city">
                @foreach(app('city')->all() as $city)
                    <option value="{{ route('cityIndex', $city) }}">
                        {{ $city->name }}
                    </option>
                @endforeach
            </select>
            <span class="myarrow"></span>
        </div>
        <div class="description os-text-center">
            <a class="os-link-order" href="#" id="welcome-submit-city">
                {{ __('Verify') }}
            </a>
        </div>
        <div>
            <button class="link-modal modal-close">
                {{ __('Skip') }}
            </button>
        </div>
        <button class="modal-icon-close">
            <img src="{{ asset('images/site/close.svg') }}" alt="">
        </button>
    </div>
</div>

resources/views/site/modals/marketBonus.blade.php
<div class="os-modal os-modal-market open" style="display: block">
    <div class="modal-content os-text-center os-position-relative">
        <h3>
            {{ __('We take you bonuses') }}
        </h3>
        <p>
            {{ __('Pass your phone') }}
        </p>
        <form class="card-body" action="{{ route('qrStoreSave', $marketType) }}" method="POST">
            @csrf

            <input type="tel" maxlength="50" class="os-input" style="margin-bottom: 0;" placeholder="{{ __('shop.forms.phone') }}" required autocomplete="phone" name="phone">

            <div class="description">
                <button type="submit" class="os-link-order">
                    {{ __('OK') }}
                </button>
            </div>
            <div class="description-form" style="margin-top: 0;">
                {{ __('You get bonuses after first order') }}
            </div>
        </form>
    </div>
</div>

resources/views/site/modals/qrOpinion.blade.php
<div class="os-modal os-modal-statistic open" style="display: block">
    <div class="modal-content os-text-center os-position-relative">
        <button class="modal-icon-close">
            <img src="{{ asset('images/site/close.svg') }}" alt="close">
        </button>
        <div class="description-form">
            {{ __('Help make our service better 2') }}
        </div>

        <form class="card-body" action="#" id="service-better">
            <div class="item-static os-flex os-flex-middle os-flex-between">
                <label class="static-down">
                    <input type="radio" class="os-input" name="mark" id="service-better-false" value="0" required
                        data-title="{{ __('Service bad title') }}"
                        data-html="{{ __('Service bad text') }}"
                        data-confirm="{{ __('Service bad button') }}"
                        data-href="{{ app('city')->config('service_bad', 'https://docs.google.com/forms/d/1ZdMmXXhGRDtBxKg59WrQYKhUVqCMalI3C4jB50BDiig') }}">
                    <span class="icon"></span>
                    {{ __('Service bad') }}
                </label>
                <div>
                    &nbsp;
                </div>
                <label class="static-up">
                    <input type="radio" class="os-input" name="mark" id="service-better-true" value="1" required
                        data-title="{{ __('Service good title') }}"
                        data-html="{{ __('Service good text') }}"
                        data-confirm="{{ __('Service good button') }}"
                        data-href="{{ app('city')->config('service_good', 'https://g.page/kotosushi-com-ua/review?gm') }}">
                    <span class="icon"></span>
                    {{ __('Service good') }}
                </label>
            </div>

            <div class="description">
                <button type="submit" class="os-link-order">
                    {{ __('Send') }}
                </button>
            </div>
        </form>
    </div>
</div>

resources/views/site/modals/statistic.blade.php
<div class="os-modal os-modal-statistic open" style="display: block">
    <div class="modal-content os-text-center os-position-relative">
        <button class="modal-icon-close">
            <img src="{{ asset('images/site/close.svg') }}" alt="close">
        </button>
        <div class="description-form">
            {{ __('Help make our service better') }}
        </div>

        <form class="card-body" action="{{ route('opinion.save', $opinion) }}" method="POST">
            @csrf

            @foreach (config('shop.opinion_marks') as $mark)
            <div class="item-static os-flex os-flex-middle os-flex-between">
                <label class="static-down">
                    <input type="radio" class="os-input" name="marks[{{ $mark }}]" value="0" required>
                    <span class="icon"></span>
                </label>
                <div>
                    {{ __($mark ?? '') }}
                </div>
                <label class="static-up">
                    <input type="radio" class="os-input" name="marks[{{ $mark }}]" value="1" required>
                    <span class="icon"></span>
                </label>
            </div>
            @endforeach

            <div class="description">
                <button type="submit" class="os-link-order">
                    {{ __('Send') }}
                </button>
            </div>
        </form>
    </div>
</div>

resources/views/site/modals/workTime.blade.php
<div class="os-modal os-modal-work-time">
    <div class="modal-content os-text-center os-position-relative">
        <div class="logo-type">
            <img loading="lazy" src="{{ asset('images/site/sleep.png') }}" alt="">
        </div>

        @php $workTime = app('city')->getTodayWorkTime(); @endphp
        <p>
            @if ($workTime['closed'])
                {{ __('Today is close') }}
            @else
                {{ __('Work from :from to :to', ['from' => $workTime['from']->format('H:i'), 'to' => $workTime['to']->format('H:i')]) }}
            @endif
        </p>

        <p>
            {{ __('You can do preorder') }}
        </p>
        <div class="description os-text-center">
            <a class="os-link-order modal-close" href="#">
                {{ __('Make preorder') }}
            </a>
        </div>
        <div>
            <button class="link-modal modal-close">
                {{ __('Skip') }}
            </button>
        </div>
        <button class="modal-icon-close modal-close">
            <img src="{{ asset('images/site/close.svg') }}" alt="">
        </button>
    </div>
</div>