routes/admin.php
<?php

// Dashboard
Route::get('/', 'DashboardController@dashboard')
    ->name('dashboard');

Route::resource('users', 'UserController')
    ->only('index')
    ->middleware('can:view-users');
Route::resource('users', 'UserController')
    ->except(['show', 'index'])
    ->middleware('can:manage-users');
Route::get('users/iiko', 'UserController@iiko')
    ->name('users.iiko')
    ->middleware('can:manage-users');

Route::resource('customers', 'CustomerController')
    ->only('index')
    ->middleware('can:view-customers');
Route::resource('customers', 'CustomerController')
    ->except(['index', 'show'])
    ->middleware('can:manage-customers');

Route::resource('birthdays', 'BirthdaysController')
    ->only('index')
    ->middleware('can:view-birthdays');

Route::resource('cities', 'CityController')
    ->only('index')
    ->middleware('can:view-cities');
Route::resource('cities', 'CityController')
    ->except(['index', 'show'])
    ->middleware('can:manage-cities');
Route::get('cities/iiko', 'CityController@iiko')
    ->name('cities.iiko')
    ->middleware('can:manage-cities');

Route::resource('roles', 'RoleController')
    ->only('index')
    ->middleware('can:view-roles');
Route::resource('roles', 'RoleController')
    ->except(['index', 'show'])
    ->middleware('can:manage-roles');
Route::post('permissions/store', 'RoleController@storePermission')
    ->name('permissions.store')
    ->middleware('can:manage-permissions');

Route::resource('terminals', 'TerminalController')
    ->only('index')
    ->middleware('can:view-terminals');
Route::resource('terminals', 'TerminalController')
    ->except(['index', 'show'])
    ->middleware('can:manage-terminals');
Route::get('terminals/iiko', 'TerminalController@iiko')
    ->name('terminals.iiko')
    ->middleware('can:manage-terminals');

Route::resource('categories', 'CategoryController')
    ->only('index')
    ->middleware('can:view-categories');
Route::resource('categories', 'CategoryController')
    ->except(['index', 'show'])
    ->middleware('can:manage-categories');
Route::get('categories/iiko', 'CategoryController@iiko')
    ->name('categories.iiko')
    ->middleware('can:manage-categories');

Route::resource('product-groups', 'ProductGroupController')
    ->only('index')
    ->middleware('can:view-product-groups');
Route::resource('product-groups', 'ProductGroupController')
    ->except(['index', 'show'])
    ->middleware('can:manage-product-groups');
Route::get('product-groups/iiko', 'ProductGroupController@iiko')
    ->name('product-groups.iiko')
    ->middleware('can:manage-product-groups');

Route::resource('products', 'ProductController')
    ->only('index')
    ->middleware('can:view-products');
Route::resource('products', 'ProductController')
    ->except(['index', 'show'])
    ->middleware('can:manage-products');
Route::post('products/{product}/remove-image', 'ProductController@removeImage')
    ->name('products.removeImage')
    ->middleware('can:manage-products');
Route::get('products/iiko', 'ProductController@iiko')
    ->name('products.iiko')
    ->middleware('can:manage-products');

Route::resource('achievements', 'AchievementController')
    ->only('index')
    ->middleware('can:view-achievements');
Route::resource('achievements', 'AchievementController')
    ->except(['index', 'show'])
    ->middleware('can:manage-achievements');
Route::post('achievements/{achievement}/remove-image', 'AchievementController@removeImage')
    ->name('achievements.removeImage')
    ->middleware('can:manage-achievements');

Route::resource('pages', 'PageController')
    ->only('index')
    ->middleware('can:view-pages');
Route::resource('pages', 'PageController')
    ->except(['index', 'show'])
    ->middleware('can:manage-pages');
Route::post('pages/{page}/remove-image', 'PageController@removeImage')
    ->name('pages.removeImage')
    ->middleware('can:manage-pages');

Route::resource('posts', 'PostController')
    ->only('index')
    ->middleware('can:view-posts');
Route::resource('posts', 'PostController')
    ->except(['index', 'show'])
    ->middleware('can:manage-posts');
Route::post('posts/{post}/remove-image', 'PostController@removeImage')
    ->name('posts.removeImage')
    ->middleware('can:manage-posts');

Route::resource('promos', 'PromoController')
    ->only('index')
    ->middleware('can:view-promos');
Route::get('promos/random', 'PromoController@randomQr')
    ->name('promos.random')
    ->middleware('can:manage-promos');
Route::resource('promos', 'PromoController')
    ->except(['index', 'show'])
    ->middleware('can:manage-promos');

Route::get('orders/game', 'OrderController@gameStats')
    ->name('orders.game')
    ->middleware('can:manage-orders');
Route::get('orders/iiko', 'OrderController@iiko')
    ->name('orders.iiko')
    ->middleware('can:manage-orders');
Route::resource('orders', 'OrderController')
    ->only(['index', 'show'])
    ->middleware('can:view-orders');
Route::resource('orders', 'OrderController')
    ->except(['index', 'show'])
    ->middleware('can:manage-orders');
Route::post('orders/sendtoiiko/{order}', 'OrderController@sendToIiko')
    ->name('orders.sendToIiko')
    ->middleware('can:manage-orders');

Route::get('settings', 'SettingsController@index')
    ->name('settings.index')
    ->middleware('can:view-settings');
Route::put('settings', 'SettingsController@update')
    ->name('settings.update')
    ->middleware('can:manage-settings');

Route::resource('slides', 'SlideController')
    ->only(['index'])
    ->middleware('can:view-slides');
Route::resource('slides', 'SlideController')
    ->except(['index', 'show'])
    ->middleware('can:manage-slides');
Route::post('slides/{slide}/remove-image', 'SlideController@removeImage')
    ->name('slides.removeImage')
    ->middleware('can:manage-slides');

Route::get('opinions', 'OpinionController@index')
    ->name('opinions.index')
    ->middleware('can:view-opinions');

Route::get('market-bonuses', 'MarketBonusController@index')
    ->name('marketBonuses.index')
    ->middleware('can:view-market-bonuses');

Route::resource('bowl-ingredients', 'BowlIngredientController')
    ->only('index')
    ->middleware('can:view-bowl-ingredients');
Route::resource('bowl-ingredients', 'BowlIngredientController')
    ->except(['index', 'show'])
    ->middleware('can:manage-bowl-ingredients');

Route::get('translations', 'SettingsController@translations')
    ->name('settings.translations')
    ->middleware('can:manage-translations');

Route::post('upload-image', 'DashboardController@uploadImage');

Route::resource('marks', 'MarkController')
    ->only('index')
    ->middleware('can:view-marks');
Route::resource('marks', 'MarkController')
    ->except(['index', 'show'])
    ->middleware('can:manage-marks');

// Telegram bot
Route::resource('telegram/groups', 'TelegramGroupController')
    ->only('index')
    ->middleware('can:view-telegram-groups');
Route::resource('telegram/groups', 'TelegramGroupController')
    ->except(['index', 'show'])
    ->middleware('can:manage-telegram-groups');
Route::post(
    'telegram/groups/{group}/send-message',
    'TelegramGroupController@sendMessage'
)->name('groups.sendMessage')
    ->middleware('can:manage-telegram-groups');

Route::resource('telegram/tasks', 'TelegramTaskController')
    ->only('index')
    ->middleware('can:view-telegram-tasks');
Route::resource('telegram/tasks', 'TelegramTaskController')
    ->except(['index', 'show'])
    ->middleware('can:manage-telegram-tasks');
Route::get('telegram/export', 'TelegramTaskController@export')
    ->name('tasks.export')
    ->middleware('can:view-telegram-tasks');

// Artisan
Route::get('artisan', 'DashboardController@artisan')
    ->name('artisan')
    ->middleware('can:run-commands');

Route::resource('callbacks', 'CallbackController')
    ->only('index')
    ->middleware('can:view-callbacks');

Route::resource('notifications', 'NotificationsController')
    ->only(['create', 'store', 'index'])
    ->middleware('can:manage-notifications');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index')
    ->name('index');
Route::get('test', 'SiteController@test')
    ->name('test');

// Opinions
Route::get('r/{opinion:slug}', 'SiteController@opinion')
    ->name('opinion');
Route::post('r/{opinion:slug}', 'SiteController@opinionSave')
    ->name('opinion.save');
Route::get('qr/{promo:qr_code}', 'SiteController@qrCode')
    ->name('qr');
Route::get('qro', 'SiteController@qrOpinion')
    ->name('qrOpinion');

// Application QR code redirect
Route::get('{type}', 'SiteController@qrStore')
    ->where('type', 'ios|android')
    ->name('qrStore');
Route::post('{type}', 'SiteController@qrStoreSave')
    ->where('type', 'ios|android')
    ->name('qrStoreSave');

// Payments
Route::post('liqpay-status', 'SiteController@liqpayStatus')
    ->name('liqpayStatus');

Auth::routes();

// Telegram bot
Route::post('telegram/webhook', 'SiteController@telegramWebhook');

Route::middleware('auth')->group(function () {
    Route::get('account', 'AccountController@index')
        ->name('account');
    Route::put('account', 'AccountController@update')
        ->name('updateAccount');

    Route::post('subscriptions', 'PushController@update');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('lang', 'AjaxController@getLangTexts');
    Route::any('basket/add', 'BasketController@add')
        ->name('basket.add');
    Route::any('basket/repeat/{order}', 'BasketController@repeat')
        ->name('basket.repeat');
    Route::any('basket/remove', 'BasketController@remove')
        ->name('basket.remove');
    Route::any('order', 'BasketController@order')
        ->name('basket.order');
    Route::get('order-track/{order}', 'AjaxController@orderTrack')
        ->name('basket.orderTrack');
    Route::any('basket', 'BasketController@basket')
        ->name('basket');
    Route::get('streets.json', 'AjaxController@streets');
    Route::post('callback', 'AjaxController@callback')
        ->name('callback');
    Route::get('find-bowl', 'AjaxController@findBowl');
    Route::get('how-many-kotcoins', 'AjaxController@howManyKotcoins')
        ->name('howManyKotcoins');
    Route::put('game-score', 'AjaxController@gameScore')
        ->name('gameScore');
    Route::get('valid-promo', 'AjaxController@validPromo')
        ->name('validPromo');
});

app/Models/Post.php
<?php

namespace App\Models;

use App\Library\HasMeta;
use App\Library\HasTranslations;
use App\Traits\TimestampSerializable;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Intervention\Image\ImageManagerStatic;

class Post extends Model
{
    use Sluggable, HasMeta, HasTranslations, TimestampSerializable;

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'city_id',
        'slug',
        'description',
        'content',
        'created_at',
        'image',
        'is_active',
        'priority',
    ];

    /**
     * @var array
     */
    public $translatable = ['name', 'content', 'description'];

    /**
     * @var array
     */
    public $casts = [
        'city_id' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'is_active' => 'boolean',
        'priority' => 'integer',
    ];

    /**
     * @var array
     */
    protected $attributes = [
        'is_active' => true,
    ];

    /**
     * @var array
     */
    protected $appends = ['link'];

    /**
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug'
        ];
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function city()
    {
        return $this->belongsTo('App\Models\City');
    }

    /**
     *
     */
    public function scopeActive($query)
    {
        return $query->whereIsActive(true)->orderBy('created_at', 'desc')->orderBy('priority');
    }

    /**
     * @param [type] $query
     *
     * @return void
     */
    public function scopeInCity($query)
    {
        return $query->where(function ($query) {
            $query->whereCityId(app('city')->id)->orWhere('city_id', null);
        });
    }

    /**
     * @param [type] $value
     *
     * @return void
     */
    public function getImageAttribute($value)
    {
        $imageUrl = $value ? asset($value) : null;
        return $imageUrl ? ($imageUrl . '?' . $this->updated_at->getTimestamp()) : null;
    }

    /**
     * @param string $value
     *
     * @return string
     */
    public function getWebpImageAttribute($value)
    {
        return str_replace(['.png', '.jpg', '.jpeg'], '.webp', $this->image);
    }

    /**
     * @param \Illuminate\Http\UploadedFile $file
     *
     * @return array
     */
    public function saveImage(UploadedFile $file)
    {
        $ext = $file->guessExtension();
        $fileName = "{$this->id}.${ext}";

        $savedName = $file->storePubliclyAs('public/posts', $fileName);
        $savedName = str_replace('public/', 'storage/', $savedName);
        ImageManagerStatic::make($file->getRealPath())
            ->encode('webp')
            ->save(storage_path("app/public/posts/{$this->id}.webp"));
        $this->update([
            'image' => asset($savedName),
        ]);
    }

    /**
     * Return previous post
     *
     * @return bool
     */
    public function prev()
    {
        $posts = self::orderBy('created_at')->pluck('id')->toArray();
        $key = array_search($this->id, $posts);
        $post = self::select('id', 'name', 'slug')->find($posts[$key - 1] ?? null);
        $this->prev = $post;

        return isset($post);
    }

    /**
     * Return next post
     *
     * @return bool
     */
    public function next()
    {
        $posts = self::orderBy('created_at')->pluck('id')->toArray();
        $key = array_search($this->id, $posts);
        $post = self::select('id', 'name', 'slug')->find($posts[$key + 1] ?? null);
        $this->next = $post;

        return isset($post);
    }

    /**
     * Return interested posts
     *
     * @return array
     */
    public function interested()
    {
        return self::joinMeta()
            ->where('metas.is_active', 1)
            ->orderBy('created_at', 'desc')
            ->whereNotIn('posts.id', [$this->id])
            ->select('posts.*');

        // $posts = self::orderBy('priority')->pluck('id')->toArray();
        // $key = array_search($this->id, $posts);

        // if ($key - $this->interestedCount >= 0) {
        //     $before = array_slice($posts, $key - $this->interestedCount, $this->interestedCount);
        //     $after = [];
        // } else {
        //     $before = array_slice($posts, 0, $key);
        //     $after = array_slice($posts, $key - $this->interestedCount, $this->interestedCount);
        // }

        // $postsIds = array_unique(array_merge($before, $after));
        // $keyy = array_search($this->id, $postsIds);
        // if ($keyy !== false) {
        //     unset($postsIds[$keyy]);
        // }

        // return self::whereIn('id', $postsIds);
    }

    /**
     * @return bool
     */
    public function getLinkAttribute()
    {
        return route('post', [app('city'), $this]);
    }
}

resources/views/site/pages/basket.blade.php
@extends('site.app')

@section('content')

<h1 class="order-title">{{ $page->name }}</h1>
<section class="order-content">
    <div class="payment" id="basket-form">
        <main-basket
            submit-url="{{ route('ajax.basket.order') }}"
            :payments='@json(app('city')->payments)'
            user-name="{{ auth()->user()->name ?? '' }}"
            user-phone="{{ auth()->user()->phone ?? '' }}"
            :cities='@json(app('city')->whereIsActive(true)->pluck('name', 'id'))'
            :city='@json(app('city'))'
            start-date="{{ now()->addMinutes(122)->format('Y-m-d') }}"
            start-time="{{ now()->addMinutes(122)->format('H:i') }}"
            :min-basket-sum="{{ config('shop.min_basket_sum') }}"
            :min-basket-payment-sum="{{ config('shop.min_basket_payment_sum') }}"
            :kotcoin-rate="{{ 1 }}"
            start-promo="{{ request()->cookie('promo') ?? '' }}"
        />

        <div class="download-app">
            <span class="download-app-text">{!! __('shop.basket.download_app') !!}</span>
            <button class="app-link">
                <a href="{{ config('site.store_links.app_store') }}">
                    <img loading="lazy" src="{{ asset('images/site/app_store.svg') }}" alt="AppStore" class="app-image">
                </a>
            </button>
            <button class="app-link">
                <a href="{{ config('site.store_links.google_play') }}">
                    <img loading="lazy" src="{{ asset('images/site/google_play.svg') }}" alt="Google Play" class="app-image">
                </a>
            </button>
        </div>
    </div>
    <basket-items></basket-items>
</section>
<div class="sauce-description ck-content">{!! $page->meta->content ?? '' !!}</div>

@if (Agent::isMobile())
    <section class="left-bottom store-links os-text-center">
        <div class="left-bottom-text">{{ __('Download our app') }}</div>
        <button class="app-link">
            <a href="{{ config('site.store_links.app_store') }}">
                <img loading="lazy" src="{{ asset('images/site/app_store.png') }}" alt="AppStore" class="app-image">
            </a>
        </button>
        <button class="app-link">
            <a href="{{ config('site.store_links.google_play') }}">
                <img loading="lazy" src="{{ asset('images/site/google_play.svg') }}" alt="Google Play" class="app-image">
            </a>
        </button>
    </section>
@endif

@if (app('order')->recommends()->count())
<div class="recommend-product">
    <span class="os-text-uppercase title-02">
        {{ __('Worth to try') }}
    </span>
    <div class="catalog-items">
        <div class="os-child-width-1-4 os-grid">
            @foreach (app('order')->recommends()->get() as $recommendProduct)
                @include('site.partials.productCatalogItem', ['product' => $recommendProduct])
            @endforeach
        </div>
    </div>
</div>
@endif

@include('site.modals.delivery')

@endsection

@if (app('city')->getDeliveryTime() == 59)
@push('scripts')
    <script>
        if (! sessionStorage.getItem('overloadedConfirmed')) {
            setTimeout(function () {
                Swal.fire({
                    title: '{{ __('Attend') }}',
                    html: '<p>{{ __('We overloaded') }}</p><p><small>{{ __('We overloaded small') }}</small></p>',
                    confirmButtonText: '{{ __('shop.push_confirm') }}',
                    customClass: {
                        title: 'swal2-title color',
                    }
                }).then((result) => {
                    if (result.isConfirmed) {
                        sessionStorage.setItem('overloadedConfirmed', true)
                    }
                })
            }, 1000)
        }
    </script>
@endpush
@endif

@if (app('city')->getDeliveryTime() == 0)
@push('scripts')
    <script>
        if (! sessionStorage.getItem('overloadedConfirmed')) {
            setTimeout(function () {
                Swal.fire({
                    title: '{{ __('shop.push_title') }}',
                    text: '{{ __('validation.is_overloaded') }}',
                    confirmButtonText: '{{ __('shop.push_confirm') }}'
                }).then((result) => {
                    if (result.isConfirmed) {
                        sessionStorage.setItem('overloadedConfirmed', true)
                    }
                })
            }, 1000)
        }
    </script>
@endpush
@endif

resources/views/site/pages/category.blade.php
@extends('site.app')

@if (request()->has('marks') || request()->has('sort'))
@section('meta.robots', 'noindex, nofollow')
@endif

@section('content')

<section>
    <div class="os-container">
        <ul class="os-breadcrumb os-flex">
            <li><a href="{{ app('city')->getIndexUrl() }}">{{ __('Main page') }}</a></li>
            <li><span>{{ $category->name }}</span></li>
        </ul>
        <nav class="category-menu-mobile os-text-center nav-category">
            @include('site.partials.categories')
            {{-- <a href="{{ route('page', [app('city'), 'bonus']) }}" class="menu-item{{ request()->is('/*/bonus') ? ' active' : '' }}">
                <img src="{{ asset("images/site/present.svg") }}" alt="bonus" class="left-menu-image">
                <div class="menu-text">{{ \App\Models\Page::whereSlug('bonus')->firstOrNew()->name }}</div>
            </a> --}}
        </nav>
        <h1 class="title-page">{{ $category->name }}</h1>
        <div class="catalog-sort">
            <button class="os-btn-sort">
                <span class="os-flex-inline os-flex-middle arrow-controls">
                    <img src="{{ asset('images/site/controls.svg') }}" alt="controls">
                    {{ __('Filter') }}
                </span>
                <img src="{{ asset('images/site/arrow-color.svg') }}" alt="arrow">
            </button>

            @include('site.partials.categoryFilter')
        </div>
        {{--@if ($category->id === (int) config('site.bowls_category_id'))--}}
            {{--<button class="os-btn-bowles mb">--}}
                {{--<span class="os-flex-inline os-flex-middle arrow-controls">--}}
                    {{--<img src="{{ asset('images/site/bowls_constructor.svg') }}" alt="bowls_constructor">--}}
                    {{--{{ __('shop.bowl_constructor.title') }}--}}
                {{--</span>--}}
                {{--<img src="{{ asset('images/site/arrow-color.svg') }}" alt="arrow">--}}
            {{--</button>--}}
        {{--@endif--}}
        <div class="catalog-items">
            <div class="os-grid">
                @if ($category->id === (int) config('site.bowls_category_id'))
                    @include('site.partials.bowlCatalogItem')
                @endif
                @foreach ($products as $product)
                    @include('site.partials.productCatalogItem', ['product' => $product])
                @endforeach
            </div>
            <div class="os-description ck-content">
                {!! $category->meta->content ?? '' !!}
            </div>
        </div>
    </div>
</section>

<div class="mobile-filter">
    <div class="mobile-menu-content os-position-relative">
        <div class="top-mobile-menu">
            {{ __('Filter') }}
        </div>
        <button class="menu-button-close">
            <img src="{{ asset('images/site/close.svg') }}" alt="close">
        </button>

        @include('site.partials.categoryFilter')
    </div>
</div>

@if ($category->id === (int) config('site.bowls_category_id'))
    @include('site.modals.bowlConstructor')
@endif

@endsection

resources/views/site/pages/cotcoins.blade.php
@extends('site.app')

@section('content')

<article>
    <div class="page page-catcoin">
        <div class="os-grid">
            <div class="os-width-2-3">

                <h1 class="title-page">
                    {{ $page->name }}
                </h1>

                <div class="description ck-content">
                    {!! $page->meta->content ?? '' !!}
                </div>

                <how-many-kotcoins
                    source-url="{{ route('ajax.howManyKotcoins') }}"
                ></how-many-kotcoins>

                <div class="os-text-center">
                    <a class="link-page" href="{{ route('category', [app('city'), \App\Models\Category::menu()->first()]) }}">
                        {{ __('Go to catalog') }}
                    </a>
                </div>
            </div>

            <div class="os-width-1-3 page-other-news">
                <div class="front-news">
                    @foreach (\App\Models\Post::active()->inCity()->limit(3)->get() as $post)
                        @include('site.partials.postCardItem', ['post' => $post])
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</article>

@endsection

resources/views/site/pages/main.blade.php
@extends('site.app')

@section('content')

<section>
    <div class="main-block os-flex">
        <div class="front-slider">
                <div class="slider slider-main">
                    @foreach ($slides as $slide)
                    <div>
                        <div class="image os-flex">
                            <div class="bestsellers">
                                <div class="seo-block">
                                    <span class="title-01">
                                        {{ $slide->title }}
                                    </span>
                                    <div class="description">
                                        <p>
                                            {{ $slide->text }}
                                        </p>
                                        <a class="os-link-order" href="{{ $slide->button_link }}">
                                            {{ $slide->button_text }}
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <a href="{{ $slide->button_link }}">
                                <picture>
                                    <source srcset="{{ $slide->webp_image }}" type="image/webp">
                                    <img loading="lazy" src="{{ $slide->image }}" alt="slide">
                                </picture>
                            </a>
                        </div>
                    </div>
                    @endforeach
                </div>
        </div>
    </div>
</section>

<section>
    <div class="cards-last">
        <span class="os-text-uppercase title-02">
            {{ __('Top products') }}
        </span>
        <div class="slider slider-hit">
            @foreach ($topProducts as $product)
                @include('site.partials.productCardItem', ['product' => $product, 'hideIngredients' => true])
            @endforeach
        </div>
    </div>
</section>

<nav class="category-menu-mobile os-text-center front-category-menu">
    @include('site.partials.categories')
    {{-- @if (\App\Models\Page::whereSlug('bonus')->active()->count())
    <a href="{{ route('page', [app('city'), 'bonus']) }}" class="menu-item{{ request()->is('/*/bonus') ? ' active' : '' }}">
        <img src="{{ asset("images/site/present.svg") }}" alt="bonus" class="left-menu-image">
        <div class="menu-text">{{ \App\Models\Page::whereSlug('bonus')->firstOrNew()->name }}</div>
    </a>
    @endif --}}
</nav>

<section>
    <div class="advantages">
        <div class="description ck-content">
            <h1>{{ __('Main page title') }}</h1>
            {!! $page->meta->content ?? '' !!}
        </div>
        <div class="os-child-width-1-4 os-grid">
            <div>
                <div class="os-flex item">
                    <div>
                        <img loading="lazy" src="{{ asset('images/site/delivery.png') }}" alt="image">
                    </div>
                    <div class="os-flex-1">
                        <div class="title os-text-uppercase">
                            {{ __('Main box 1 title') }}
                        </div>
                        <div class="sub-title">
                            {{ __('Main box 1 description') }}
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="os-flex item">
                    <div>
                        <img loading="lazy" src="{{ asset('images/site/cat.png') }}" alt="image">
                    </div>
                    <div class="os-flex-1">
                        <div class="title os-text-uppercase">
                            {{ __('Main box 2 title') }}
                        </div>
                        <div class="sub-title">
                            {{ __('Main box 2 description') }}
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="os-flex item">
                    <div>
                        <img loading="lazy" src="{{ asset('images/site/tasty.png') }}" alt="image">
                    </div>
                    <div class="os-flex-1">
                        <div class="title os-text-uppercase">
                            {{ __('Main box 3 title') }}
                        </div>
                        <div class="sub-title">
                            {{ __('Main box 3 description') }}
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="os-flex item">
                    <div>
                        <img loading="lazy" src="{{ asset('images/site/cat_up.png') }}" alt="image">
                    </div>
                    <div class="os-flex-1">
                        <div class="title os-text-uppercase">
                            {{ __('Main box 4 title') }}
                        </div>
                        <div class="sub-title">
                            {{ __('Main box 4 description') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<article>
    @if (! Agent::isMobile())
    <div class="front-news">
        <div class="os-child-width-1-2 os-grid">
            @include('site.partials.postCardItem', ['post' => $topPosts->get(0), 'mediaImg' => true])
            <div>
                @include('site.partials.postCardItem', ['post' => $topPosts->get(1), 'mediaImg' => true])
                @include('site.partials.postCardItem', ['post' => $topPosts->get(2), 'mediaImg' => true])
            </div>
        </div>
    </div>
    @endif
    <div class="front-news-mobile">
        <span class="title-02 os-text-uppercase">{{ __('Stocks and kotcoins') }}</span>
        <div class="slider slider-news">
            @foreach ($topPosts as $post)
                @include('site.partials.postCardItem', ['post' => $post, 'mobileFlex' => true])
            @endforeach
        </div>
    </div>
</article>

@if (Agent::isMobile())
<section class="left-bottom store-links">
    <div class="left-bottom-text">{{ __('Download our app') }}</div>
    <button class="app-link">
        <a href="{{ config('site.store_links.app_store') }}">
            <img loading="lazy" src="{{ asset('images/site/app_store.png') }}" alt="AppStore" class="app-image">
        </a>
    </button>
    <button class="app-link">
        <a href="{{ config('site.store_links.google_play') }}">
            <img loading="lazy" src="{{ asset('images/site/google_play.svg') }}" alt="Google Play" class="app-image">
        </a>
    </button>
</section>
@endif

<section>
    <div class="front-product-top">
        <span class="title-02 os-text-uppercase">{{ __('Top ramens') }}</span>

        @foreach ($topRamens as $product)
            @include('site.partials.productRamenItem', ['product' => $product])
        @endforeach
    </div>
</section>

@endsection

resources/views/site/pages/marketBonus.blade.php
@extends('site.app')

@section('content')

@include('site.modals.marketBonus')

@endsection